- platform: template
  sensors:
    power_strip_1_load_power:
      unit_of_measurement: "Wh"
      value_template: "{{ states.switch.power_strip_1.attributes.load_power | float }}"
    power_strip_2_load_power:
      unit_of_measurement: 'Wh'
      value_template: "{{ states.switch.power_strip_2.attributes.load_power | float }}"
    power_strip_3_load_power:
      unit_of_measurement: 'Wh'
      value_template: "{{ states.switch.power_strip_3.attributes.load_power | float }}"
    power_strip_4_load_power:
      unit_of_measurement: 'Wh'
      value_template: "{{ states.switch.power_strip_4.attributes.load_power | float }}"
