- platform: template
  sensors:
    dima_is_home:
      value_template: >
        {% if states.device_tracker.google_maps_111683533988744565132.state == 'home' %}
          true
        {% else %}
          false
        {% endif %}
    alyona_is_home:
      value_template: >
        {% if states.device_tracker.google_maps_115914092349482836896.state == 'home' %}
          true
        {% else %}
          false
        {% endif %}
    yury_is_home:
      value_template: >
        {% if states.device_tracker.google_maps_117454969161947422882.state == 'home' %}
          true
        {% else %}
          false
        {% endif %}
    parents_are_home:
      value_template: >
        {% if states.sensor.dima_is_home.state == 'true' and states.sensor.alyona_is_home.state == 'true' %}
          true
        {% else %}
          false
        {% endif %}