- alias: "light_button_single_when_light_is_on"
  initial_state: "on"
  trigger:
  - platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0002136276
      click_type: single
  condition:
  - condition: state
    entity_id: light.livingroom_ambient
    state: "on"
  action:
  - service: script.light_turn_off_flow
  - service: light.turn_off
    entity_id: light.livingroom_ambient

- alias: "light_button_single_when_light_is_off"
  initial_state: "on"
  trigger:
  - platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0002136276
      click_type: single
  condition:
  - condition: state
    entity_id: light.livingroom_ambient
    state: "off"
  action:
  - service: script.light_turn_on_livingroom_torch_by_params
  - service: script.light_turn_on_livingroom_corner_by_params

- alias: "light_livingroom_flow"
  initial_state: "on"
  trigger:
    platform: time
    seconds: "/5"
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: input_boolean.livingroom_torch_use
      state: "on"
    - condition: state
      entity_id: input_boolean.livingroom_corner_use
      state: "on"
  action:
  - service: script.flow_idx_update
  - service: script.light_turn_on_hs
    data_template:
      id: >
        {% if is_state('input_boolean.livingroom_torch_use', 'on') and is_state('input_boolean.livingroom_corner_use', 'on') %}
          light.livingroom_torch,light.livingroom_corner
        {% elif is_state('input_boolean.livingroom_torch_use', 'on') %}
          light.livingroom_torch
        {% elif is_state('input_boolean.livingroom_corner_use', 'on') %}
          light.livingroom_corner
        {% endif %}
      hue: >
        {% set hue = {
          1 : states.input_number.flow_hue1.state | int,
          2 : states.input_number.flow_hue2.state | int,
          3 : states.input_number.flow_hue3.state | int,
          4 : states.input_number.flow_hue4.state | int
        } %}
        {{hue[states.input_number.flow_idx.state|int]}}
      sat: "{{ states.input_number.flow_saturation.state }}"
      brightness: "{{ states.input_number.flow_brightness.state }}"
      transition: "{{ states.input_number.flow_transition.state }}"

- alias: "light_livingroom_flow_hues"
  initial_state: "on"
  trigger:
    platform: state
    entity_id: input_select.living_room_flow
  action:
  - service: input_number.set_value
    entity_id: input_number.flow_hue1
    data_template:
      value: >
        {% set hue = {
          'custom' : states.input_number.flow_custom_hue1.state,
          'purple' : 260,
          'red' : 340,
          'yellow' : 40,
          'green' : 100,
          'blue' : 200
        } %}
        {{hue[states.input_select.living_room_flow.state]}}
  - service: input_number.set_value
    entity_id: input_number.flow_hue2
    data_template:
      value: >
        {% set hue = {
          'custom' : states.input_number.flow_custom_hue2.state,
          'purple' : 280,
          'red' : 360,
          'yellow' : 60,
          'green' : 120,
          'blue' : 220
        } %}
        {{hue[states.input_select.living_room_flow.state]}}
  - service: input_number.set_value
    entity_id: input_number.flow_hue3
    data_template:
      value: >
        {% set hue = {
          'custom' : states.input_number.flow_custom_hue3.state,
          'purple' : 300,
          'red' : 20,
          'yellow' : 80,
          'green' : 140,
          'blue' : 240
        } %}
        {{hue[states.input_select.living_room_flow.state]}}
  - service: input_number.set_value
    entity_id: input_number.flow_hue4
    data_template:
      value: >
        {% set hue = {
          'custom' : states.input_number.flow_custom_hue4.state,
          'purple' : 320,
          'red' : 40,
          'yellow' : 100,
          'green' : 160,
          'blue' : 260
        } %}
        {{hue[states.input_select.living_room_flow.state]}}