- alias: "power_strip_computer_off"
  initial_state: "on"
  trigger:
    platform: time
    at: "02:00:00"
  action:
    service: switch.turn_off
    entity_id: switch.power_strip_1

- alias: "power_strip_computer_on"
  initial_state: "on"
  trigger:
    platform: time
    at: "06:50:00"
  action:
    service: switch.turn_on
    entity_id: switch.power_strip_1

- alias: "light_on_at_the_morning"
  initial_state: "on"
  trigger:
    platform: time
    at: "06:55:00"
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    - service: script.light_turn_on_livingroom_torch_by_params
    - service: script.light_turn_on_livingroom_corner_by_params
    - service: script.light_turn_on_entrance_garland

- alias: "light_off_at_the_morning"
  initial_state: "on"
  trigger:
    platform: time
    at: "07:35:00"
  condition:
    condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
    - service: script.light_turn_off_livingroom
    - service: script.light_turn_off_entrance_garland

- alias: "light_off_after_sunset"
  initial_state: "on"
  trigger:
  - platform: time
    at: "23:00:00"
  - platform: sun
    event: sunset
    offset: '03:00:00'
  action:
    - service: script.light_turn_off_entrance_garland

- alias: "light_on_at_the_sunset"
  initial_state: "on"
  trigger:
    platform: sun
    event: sunset
  action:
  - service: script.light_turn_on_entrance_garland