- alias: "power_strip_computer_off"
  initial_state: "on"
  trigger:
    platform: time
    at: "02:25:00"
  action:
    service: switch.turn_off
    entity_id: switch.power_strip_1

- alias: "power_strip_computer_on"
  initial_state: "on"
  trigger:
    platform: time
    at: "07:00:00"
  action:
    service: switch.turn_on
    entity_id: switch.power_strip_1