- alias: "ha_start"
  initial_state: "on"
  trigger:
  - platform: homeassistant
    event: start
  action:
  - service: telegram_bot.send_message
    data_template:
      target: !secret tg_chat_dima
      message: "{{ now().strftime('%H:%M') }} \U0001F916 {{ states.sensor.current_version.state }} HA back online!"
      inline_keyboard:
      - "\U0001F532 Menu:/menu, \U0000267B Dismiss:/dismiss"

- alias: "ha_shutdown"
  initial_state: "on"
  trigger:
  - platform: homeassistant
    event: shutdown
  action:
  - service: telegram_bot.send_message
    data_template:
      target: !secret tg_chat_dima
      message: "{{ now().strftime('%H:%M') }} \U0001F6D1 {{ states.sensor.current_version.state }} HA goes offline!"
      inline_keyboard:
      - "\U0000267B Dismiss:/dismiss"

- alias: "notification_low_battery"
  initial_state: "on"
  trigger:
    platform: numeric_state
    below: 15
    entity_id:
      - sensor.doorbell_switch_battery_level
      - sensor.door_sensor_battery_level
      - sensor.livingroom_light_switch_battery_level
      - sensor.motion1_battery_level
      - sensor.motion2_battery_level
      - sensor.t1_battery_level
      - sensor.t2_battery_level
      - sensor.t3_battery_level
      - sensor.t4_battery_level
  action:
    service: telegram_bot.send_message
    data_template:
      target: !secret tg_chat_dima
      message: "\U0001F50B {{ trigger.from_state.name }} battery level drops to {{ trigger.to_state.state }}%"