- platform: season
- platform: moon
- platform: uptime
- platform: version

- platform: filesize
  file_paths:
  - /config/home-assistant_v2.db
  type: astronomical

- platform: systemmonitor
  resources:
  - type: processor_use
  - type: memory_use_percent
  - type: memory_use
  - type: memory_free

- platform: time_date
  display_options:
    - 'time'
    - 'date'

- platform: statistics
  name: "outside_temperature"
  entity_id: sensor.temperature_158d00022c7cf2
  sampling_size: 86400
  max_age:
    hours: 24