- platform: darksky
  api_key: !secret darksky_api_key
  units: si
  forecast:
  - 1
  - 2
  - 3
  - 4
  - 5
  update_interval:
    minutes: 10
  monitored_conditions:
  - icon
  - summary
  - daily_summary
  - hourly_summary
  - minutely_summary
  - temperature
  - temperature_high
  - temperature_low
  - apparent_temperature
  - apparent_temperature_high
  - apparent_temperature_low
  - wind_speed
  - wind_bearing
  - precip_type
  - precip_probability
  - precip_accumulation
  - precip_intensity
  - precip_intensity_max
  - humidity
  - pressure
  - visibility
  - ozone